# WAP TO CHECK WHETHER THE CLIENT IS ELIGIBLE FOR VOTE OR NOT.
age=int(input('ENTER YOUR AGE :'));
if age>=18:
     print('YOU ARE ELIGIBLE FOR VOTING.');
else :
    print('YOU ARE NOT ELIGIBLE FOR VOTING.');
    
